module.exports.authService = require('./auth')
module.exports.userService = require('./user')
module.exports.tokenService = require('./token')
module.exports.productService = require('./product')
module.exports.categoryService = require('./category')
module.exports.offerService = require('./offer')