module.exports = {
    MESSAGES: {
        USER_ALREADY_EXISTS: 'User already exists with this email or mobile',
        USER_NOT_EXIST: 'User does not exist with this email or mobile',
        INCORRECT_PASSWROD: 'Incorrect password',
        USER_NOT_FOUND: 'User not found',
        INCORRECT_OTP: 'Incorrect OTP',
        SOMETHING_WENT_WRONG: 'Something went wrong, please try again',
        AUTHENTICATION_FAILED: 'Authentication failed',
        INVALID_TOKEN: 'Invalid token',
        ENTER_VALID_CATEGORY: 'Please enter valid category',
        PRODUCTS_NOT_FOUND: 'Products not found for this category',
        PRODUCT_NOT_FOUND: 'Product not found for this productId',
        REVIEW_NOT_FOUND: 'Review not found with this reviewId',
        USER_NOT_ALLOWED: 'User is not allowed to modify this resource',
        TOGGLE_PARAM_MISSING: 'Please enter a toggle query parameter',
        ENTER_VALID_ACTION: 'Please enter a valid cart action',
        ADD_PRODUCT_TO_CART: 'Please first add product to cart',
        ADDRESS_NOT_FOUND: 'Address not found for this user or addressId',
        SHIPPING_NOT_FOUND: 'Shipping-type not found with this Id',
        ENTER_VALID_OBJECTID: 'Invalid ID. Please provide a valid ObjectId',
        PROMO_NOT_FOUND: 'Promo-code expired or not found with this Id',
        INCORRECT_PIN: 'Incorrect PIN. Please enter correct PIN',
        ORDER_NOT_FOUND: 'Order not found for this user or orderId',
        ADD_PRODUCTS: 'Please add products to cart first to checkout',
        AMOUNT_NOT_MATCH: 'Amount not match! please check the total amount',
        PAYMENT_METHOD_NOT_FOUND: 'Payment-method not found for this user or paymentId',
        PAYMENT_METHOD_EXPIRED: 'Payment-method expired, please add a new payment-method',
        INSUFFICIENT_BALANCE: 'Not have sufficient balance'
    },
    COLLECTIONS: {
        USER: 'User',
        PRODUCT: 'Product',
        CATEGORY: 'Category',
        REVIEW: 'Review',
        NOTIFICATION: 'Notification',
        WISHLIST: 'Wishlist',
        OFFER: 'Offer',
        CART: 'Cart',
        ORDER: 'Order',
        ADDRESS: 'Address',
        PROMOTION: 'Promotion',
        PAYMENTMETHOD: 'PaymentMethod',
        SHIPPINGTYPE: 'ShippingType'
    }
}
